# Generated by Django 4.0.2 on 2022-06-20 12:58

import Extentions.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDegreeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('degree_image', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.doctor_degree_path, verbose_name='تصویر مدرک')),
                ('medical_system_code', models.IntegerField(blank=True, null=True, verbose_name='کد نظام پزشکی')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پدر')),
                ('birth_certificate_id', models.BigIntegerField(blank=True, null=True, verbose_name='شماره شناسنامه')),
                ('national_code', models.BigIntegerField(blank=True, null=True, verbose_name='کدملی')),
                ('issued_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='صادره از')),
                ('degree_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('average', models.FloatField(blank=True, null=True, verbose_name='معدل')),
                ('average_chars', models.CharField(blank=True, max_length=255, null=True, verbose_name='معدل با حروف')),
                ('medical_field_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام رشته')),
                ('is_valid', models.BooleanField(default=False, help_text='آیا این مدرک تایید شده است؟', verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تخصص پزشک',
                'verbose_name_plural': 'تخصص \u200cهای پزشکان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, null=True, verbose_name='سابقه ی پزشکی')),
                ('bio', models.TextField(blank=True, help_text='این متن در زمان ارائه\u200cی مقالات پزشکی شما در سایت، به کاربران نشان داده خواهد شد', max_length=500, null=True, verbose_name='بیوگرافی')),
                ('is_advised', models.BooleanField(default=False, help_text='اگر این گزینه فعال این پزشک میتواند برنامه\u200cی پزشکی تعیین کند و وقت مشاوره ارائه بدهد', verbose_name='اجازه برای مشاوره دادن به بیماران')),
                ('send_doctor_request_for_blogging', models.BooleanField(default=False, help_text='آیا این پزشک درخواست برای بلاگنویسی داده است؟', verbose_name='درخواست وبلاگنویسی')),
                ('is_blogger', models.BooleanField(default=False, help_text='اجازه\u200cی نوشتن مقالات', verbose_name='نویسنده است؟')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشک ها',
                'ordering': ['-user__id'],
            },
        ),
        migrations.CreateModel(
            name='TitleSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تخصص')),
            ],
            options={
                'verbose_name': 'عنوان تخصص',
                'verbose_name_plural': 'عناوین تخصص\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('finance', 'Finance and Administration'), ('ac_activation', 'Account Activation'), ('ac_upgrade', 'Upgrade Account'), ('webSite_performance', 'WebSite Performance'), ('other', 'Other')], max_length=100, null=True, verbose_name='دپارتمان')),
                ('subject', models.CharField(blank=True, max_length=225, null=True, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.ticket_image_path, verbose_name='تصویر')),
                ('is_read_user', models.BooleanField(default=False, verbose_name='خوانده شده توسط کاربر؟')),
                ('is_read_supporter', models.BooleanField(default=False, verbose_name='خوانده شده توسط پشتیبان؟')),
                ('is_reply', models.BooleanField(default=False, verbose_name='آیا این تیکت پاسخ است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.ticketmodel', verbose_name='پاسخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupportersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_send_reply', models.BooleanField(default=False, verbose_name='اجازه\u200cی ارسال پاسخ به کاربران')),
                ('is_create_blog', models.BooleanField(default=False, verbose_name='اجازه\u200cی تولید پست')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پشتیبان',
                'verbose_name_plural': 'پشتیبانان',
                'ordering': ['-user__id'],
            },
        ),
        migrations.CreateModel(
            name='ReportChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=255, verbose_name='نوع گزارش')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False, verbose_name='رسیدگی شده است؟')),
                ('reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_chat', to=settings.AUTH_USER_MODEL, verbose_name='گزارش شده')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_chat', to=settings.AUTH_USER_MODEL, verbose_name='گزارش کننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MessagePermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=255, null=True, verbose_name='تخصص پزشک')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال بودن چت')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.doctormodel', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'اجازه\u200cی چت',
                'verbose_name_plural': 'اجازه\u200cی چت\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to=Extentions.utils.file_chat_path, verbose_name='فایل')),
                ('is_send', models.BooleanField(default=False, verbose_name='فرستاده شد؟')),
                ('is_seen', models.BooleanField(default=False, verbose_name='دیده شد؟')),
                ('is_reply', models.BooleanField(default=False, verbose_name='آیا این پیام پاسخ میباشد؟')),
                ('have_file', models.BooleanField(default=False, verbose_name='آیا این پیام شامل فایل میباشد؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('msg_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.messagepermissionmodel', verbose_name='اجازه\u200cی چت')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.messagemodel', verbose_name='پاسخ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'چت',
                'verbose_name_plural': 'چت ها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReservingTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedtime_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='روز درخواستی از سمت بیمار')),
                ('requestedtime_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='ساعت درخواستی از سمت بیمار')),
                ('is_doctor_see', models.BooleanField(default=False, verbose_name='آیا پزشک این درخواست را مشاهده کرده است؟')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ملاقات با دکتر')),
                ('visit_timefrom', models.TimeField(blank=True, null=True, verbose_name='زمان ملاقات با دکتر از')),
                ('visit_timeto', models.TimeField(blank=True, null=True, verbose_name='زمان ملاقات با دکتر تا')),
                ('is_active', models.BooleanField(default=False, verbose_name='آیا این زمان رزرو شده است؟')),
                ('is_ended', models.BooleanField(default=False, verbose_name='آیا این ملاقات به اتمام رسیده است؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.doctormodel', verbose_name='پزشک')),
                ('doctor_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.doctordegreemodel', verbose_name='تخصص پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'زمان ملاقات پزشک',
                'verbose_name_plural': 'زمان\u200cهای ملاقات پزشک',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='doctordegreemodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.doctormodel', verbose_name='پزشک'),
        ),
        migrations.AddField(
            model_name='doctordegreemodel',
            name='skill_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.titleskillmodel', verbose_name='عنوان تخصص/ها'),
        ),
        migrations.CreateModel(
            name='DoctorConsultingTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنج شنبه'), ('friday', 'جمعه')], max_length=15, null=True, verbose_name='روز')),
                ('time', models.CharField(blank=True, choices=[('6-8', '6-8'), ('8-10', '8-10'), ('10-12', '10-12'), ('12-14', '12-14'), ('14-16', '14-16'), ('16-18', '16-18'), ('18-20', '18-20')], max_length=15, null=True, verbose_name='زمان')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampool_jobs.doctormodel', verbose_name='پزشک')),
                ('skill', models.ManyToManyField(to='ampool_jobs.DoctorDegreeModel', verbose_name='تخصص\u200cها')),
            ],
            options={
                'verbose_name': 'زمان مشاوره\u200cی پزشک',
                'verbose_name_plural': 'زمان\u200cهای مشاوره\u200cی پزشک',
                'ordering': ['-id'],
            },
        ),
    ]
